django_todolist/django_todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('todolist.urls')),
]

django_todolist/todolist/urls.py
from django.urls import path
from . import views
from .views import list_todo
from .views import TaskCreate
from .views import TaskUpdate
from .views import TaskDelete


app_name = 'todolist'
urlpatterns = [
    path('',list_todo.as_view(), name='tasks'),
    path('create-task/', TaskCreate.as_view(), name='create-task'),
    path('update-task/<int:pk>/', TaskUpdate.as_view(), name='update-task'),
     path('delete-task/<int:pk>/', TaskDelete.as_view(), name='delete-task'),
]


# IndexViewに処理を移す

django_todolist/todolist/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    # Taskクラスを作成
    title = models.CharField(max_length=100)
    # タイトルは100文字までの文字列
    created = models.DateTimeField(auto_now_add=True)
    # 作成日時は自動で現在の日時が入る
    completed = models.BooleanField(default=False)
    # 完了フラグはデフォルトでFalse

    def __str__(self):
        return self.title
    # タイトルを返す

django_todolist/todolist/views.py
from django.views.generic.list import ListView
from .models import Task
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.

# ここで、list_todo関数を定義して、task.htmlを返す
class list_todo(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task.html'

class TaskCreate(CreateView):
    model = Task
    fields = "__all__"
    template_name = 'task_form.html'
    success_url = reverse_lazy('todolist:tasks')

class TaskUpdate(UpdateView):
    model = Task
    fields = "__all__"
    template_name = 'task_Update.html'
    success_url = reverse_lazy('todolist:tasks')

class TaskDelete(DeleteView):
    model = Task
    fields = "__all__"
    template_name = 'task_delete.html'
    success_url = reverse_lazy('todolist:tasks')

django_todolist/todolist/templates/task.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>ToDoリスト</title>
</head>
<body>
    <h1>ToDoリスト</h1>
    <form method="post" action="{% url 'todolist:create-task' %}">
        {% csrf_token %}
        <input type="text" name="title">
        <button type="submit">追加</button>
    </form>
    <table>
        <tr>
            <th>タスク名</th>
        </tr>
        {% for task in tasks %}
        <tr>
            
            <td>{{ task.title }}</td>
            <td><form method="post" action="{% url 'todolist:update-task' task.id %}">
                {% csrf_token %}
                <input type="text" name="title">
                <button type="submit">変更</button>
            </form></td>
            <td><form method="post" action="{% url 'todolist:delete-task' task.id %}">
                {% csrf_token %}
                <button type="submit">削除</button>
            </form></td>
            
           
        </tr>
        {%endfor%}
    </table>
  
</body>
   
</html>

django_todolist/todolist/templates/task_Update.html
{% extends "task.html" %}

{% block content %}
<h2>変更</h2>
<a href="{% url 'todolist:tasks' %}">戻る</a>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">変更</button>
</form>
{% endblock %}

django_todolist/todolist/templates/task_delete.html
{% extends 'task.html' %}

{% block content %}
<h2>削除しますか？</h2>
<a href="{% url 'todolist:tasks' %}">戻る</a>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">削除</button>
</form>
{% endblock %}

django_todolist/todolist/templates/task_form.html
{% extends "task.html" %}

{% block content %}
<h2>タスク追加</h2>
<a href="{% url 'todolist:tasks' %}">戻る</a>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">追加</button>
</form>

{% endblock %}